from ..utils.data_types import RGB, ColorData

GAMMA = 2.4
INV_GAMMA = 1 / GAMMA


def to_linear(c) -> float:
    c = c / 255.0
    if c <= 0.04045:
        return c / 12.92
    else:
        return ((c + 0.055) / 1.055) ** GAMMA


def linear_to_standard(l) -> int:
    if l <= 0.0031308:
        return round(12.92 * l * 255)
    else:
        return round(255 * (1.055 * l ** (INV_GAMMA) - 0.055))


def luma(r: int, g: int, b: int) -> float:
    """
    Calculate perceived brightness (luma) from RGB values.

    Args:
        r: Red value (0-255)
        g: Green value (0-255)
        b: Blue value (0-255)

    Returns:
        float: Luma value from 0-255
    """

    r_lin = to_linear(r)
    g_lin = to_linear(g)
    b_lin = to_linear(b)

    # Apply coefficients in linear space
    luma_linear = 0.2126 * r_lin + 0.7152 * g_lin + 0.0722 * b_lin
    return luma_linear * 255.0


def contrast_ratio(luma1: float, luma2: float) -> float:
    """
    Calculate WCAG contrast ratio between two luma values (0-255 scale).

    Formula: (L1 + 0.05) / (L2 + 0.05) where L1 > L2
    where luma values are normalized to 0-1 range.
    """
    # Normalize to 0-1 range (relative luminance)
    L1 = max(luma1, luma2) / 255.0
    L2 = min(luma1, luma2) / 255.0

    return (L1 + 0.05) / (L2 + 0.05)


def blend(color: RGB, blend_with: RGB, amount: float) -> RGB:
    """
    Blend two colors in linear RGB space.

    Args:
        color: The base color
        blend_with: The color to blend with
        amount: How much of blend_with to use (0.0 = all color, 1.0 = all blend_with)
    """
    # naming convention in case i forget
    # 1 -> color
    # 2 -> blend_with

    r_lin1 = to_linear(color.r)
    g_lin1 = to_linear(color.g)
    b_lin1 = to_linear(color.b)

    r_lin2 = to_linear(blend_with.r)
    g_lin2 = to_linear(blend_with.g)
    b_lin2 = to_linear(blend_with.b)

    r_final = linear_to_standard((1 - amount) * r_lin1 + amount * r_lin2)
    g_final = linear_to_standard((1 - amount) * g_lin1 + amount * g_lin2)
    b_final = linear_to_standard((1 - amount) * b_lin1 + amount * b_lin2)

    return RGB(r_final, g_final, b_final)


def _find_optimal_blend_for_contrast(
    target_contrast: float,
    darker_rgb: RGB,
    lighter_rgb: RGB,
    brighten_toward: RGB,
    max_blend: float = 1.0,
) -> float:
    """Direct mathematical solution using luminance calculation."""

    # NOTE: generated by AI, needs review

    # TODO: Also add options like darken_towads and set brighten and darken to None.
    # so that this func can be used for both dark and light theme

    darker_luma = luma(darker_rgb.r, darker_rgb.g, darker_rgb.b)
    lighter_luma = luma(lighter_rgb.r, lighter_rgb.g, lighter_rgb.b)
    target_luma = luma(brighten_toward.r, brighten_toward.g, brighten_toward.b)

    # Normalize to 0-1
    L_dark = darker_luma / 255.0
    L_light = lighter_luma / 255.0
    L_target = target_luma / 255.0

    # Current contrast
    current_contrast = (L_light + 0.05) / (L_dark + 0.05)
    if current_contrast >= target_contrast:
        return 0.0

    # Required luminance for target contrast
    L_required = target_contrast * (L_dark + 0.05) - 0.05

    # Cannot reach required luminance
    if L_target < L_required:
        return -1.0

    # Solve for blend factor
    denominator = L_target - L_light
    if abs(denominator) < 1e-6:
        return 0.0

    t = (L_required - L_light) / denominator
    return max(0.0, min(max_blend, t))


def _is_near_white(color: RGB, max_channel_diff: int = 50, min_luma: int = 130) -> bool:
    """
    Check if a color is close to white (desaturated and bright).

    A color is "kinda white" if:
    1. All RGB channels are similar (low saturation)
    2. The color is bright enough (high luma)

    Args:
        color: RGB color to check
        max_channel_diff: Maximum allowed difference between RGB channels (desaturation check)
        min_luma: Minimum luma value for brightness (0-255)

    Returns:
        True if color is whitish, False otherwise
    """

    # Check if desaturated (channels are similar)
    min_val = min(color.r, color.g, color.b)
    max_val = max(color.r, color.g, color.b)
    is_desaturated = (max_val - min_val) <= max_channel_diff

    # Check if bright enough
    color_luma = luma(color.r, color.g, color.b)
    is_bright = color_luma >= min_luma

    return is_desaturated and is_bright
